name: Manual OpenCode Task

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: Prompt
        required: true
        default: 'Hi!'

jobs:
  opencode:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run OpenCode
        uses: anomalyco/opencode/github@latest
        with:
          model: opencode/deepseek-v4-flash-free
          prompt: ${{ github.event.inputs.prompt }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: artifact
          path: /tmp/artifact/*
          if-no-files-found: ignore
          retention-days: 7
