name: Release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3

      - name: Create Draft Release
        env:
          GH_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ github.ref_name }}
        run: gh release create "$TAG_NAME" --draft --generate-notes --verify-tag
