name: chrome remote desktop

on:
  workflow_dispatch:
    inputs:
      code:
        description: "code"
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install winget
        run: ./install-winget.ps1

      - name: Install chrome remote desktop
        run: winget.exe install -e --id Google.ChromeRemoteDesktopHost --accept-package-agreements --accept-source-agreements

      - name: Starting chrome remote desktop
        run: |
          & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="${{ github.event.inputs.code }}" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME

      - name: Keep alive
        run: |
          $process = Start-Process notepad -PassThru
          while (-not $process.HasExited) {
              Start-Sleep -Seconds 1
          }
          Write-Host "Notepad has been closed. Exiting loop."
