name: a

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install scoop
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
          Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression

      - name: Install ngrok
        run: |
          ~\scoop\shims\scoop.ps1 install main/ngrok

      - name: Connect to ngrok
        run: ~\scoop\shims\ngrok.exe tcp 3389 --authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Keep alive
        run: |
          $process = Start-Process notepad -PassThru
          while (-not $process.HasExited) {
              Start-Sleep -Seconds 1
          }
          Write-Host "Notepad has been closed. Exiting loop."
