name: chrome remote desktop

on:
  workflow_dispatch:
    inputs:
      auth_command:
        description: "Auth command"
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install chrome remote desktop
        run: |
          Invoke-WebRequest -Uri https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi -OutFile "$Env:TEMP\chromeremotedesktophost.msi"
          Start-Process "$Env:TEMP\chromeremotedesktophost.msi" -Wait

      - name: Starting chrome remote desktop
        run: ${{ github.event.inputs.auth_command }} --pin="000000"

      - name: Keep alive
        run: |
          Stop-ScheduledTask RunnerMachineProvisioner
          Disable-ScheduledTask RunnerMachineProvisioner
