name: chrome remote desktop

on:
  workflow_dispatch:
    inputs:
      code:
        description: "code"
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install chrome remote desktop
        run: |
          Invoke-WebRequest -Uri https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi -OutFile "$Env:TEMP\chromeremotedesktophost.msi"
          & "$Env:TEMP\chromeremotedesktophost.msi"

      - name: Starting chrome remote desktop
        run: |
          & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="${{ github.event.inputs.authcode }}" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME

      - name: Keep alive
        run: |
          $process = Start-Process notepad -PassThru
          while (-not $process.HasExited) {
              Start-Sleep -Seconds 1
          }
          Write-Host "Notepad has been closed. Exiting loop."
