name: chrome remote desktop

on:
  workflow_dispatch:
    inputs:
      auth_command:
        description: "Auth command"
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install chrome remote desktop
        run: |
          Invoke-WebRequest -Uri https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi -OutFile "$Env:TEMP\chromeremotedesktophost.msi"
          Start-Process "$Env:TEMP\chromeremotedesktophost.msi" -Wait

      - name: Starting chrome remote desktop
        run: ${{ github.event.inputs.auth_command }} --pin="000000"

      - name: 
        run: |
          Stop-Service docker

      - name: Keep alive
        run: |
          Disable-ScheduledTask RunnerMachineProvisioner
          Stop-Process provisioner -Force
          Stop-Process Runner.Listener -Force
          Stop-Process provjobd -Force
          Stop-Process pwsh -Force
