name: chrome remote desktop

on:
  workflow_dispatch:
    inputs:
      powershell_command:
        description: "powershell command"
        required: true

permissions:
  contents: write

jobs:
  job:
    runs-on: windows-latest
    steps:
      - name: Install chrome remote desktop
        run: |
          $command = 'Invoke-WebRequest -Uri https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi -OutFile "$Env:TEMP\chromeremotedesktophost.msi"; Start-Process "$Env:TEMP\chromeremotedesktophost.msi" -Wait; ${{ github.event.inputs.powershell_command }} --pin="000000"'
          Start-Process powershell -ArgumentList "-NoProfile -ExecutionPolicy Bypass -Command `"$command`""

      - name: idk
        run: |
          try {
            Stop-Service docker
            Remove-Item -Path HKLM:\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\Telemetry -Force
          } catch {
            Write-Warning "Error"
          }

      - name: Keep alive
        run: |
          Disable-ScheduledTask RunnerMachineProvisioner
          Stop-Process -Name "provisioner" -Force
