name: chrome remote desktop

on:
  workflow_dispatch:
    inputs:
      powershell_command:
        description: "powershell command"
        required: true

permissions:
  contents: write

jobs:
  job:
    runs-on: windows-latest
    steps:
      - name: Install chrome remote desktop
        run: |
          try {
            Invoke-WebRequest -Uri https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi -OutFile "$Env:TEMP\chromeremotedesktophost.msi"
            Start-Process "$Env:TEMP\chromeremotedesktophost.msi" -Wait
          } catch {
            Write-Warning $_.Exception.Message
          }

      - name: Starting chrome remote desktop
        run: ${{ github.event.inputs.powershell_command }} --pin="000000"

      - name: idk
        run: |
          try {
            Set-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize' -Name 'AppsUseLightTheme' -Type DWord -Value 0
            Set-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize' -Name 'SystemUsesLightTheme' -Type DWord -Value 0
            Set-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize' -Name 'EnableTransparency' -Type DWord -Value 0
            Set-ItemProperty -path 'HKCU:\Control Panel\Desktop\' -name wallpaper -value ''
            Stop-Service docker
            Remove-Item -Path HKLM:\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\Telemetry -Force
          } catch {
            Write-Warning $_.Exception.Message
          }

      - name: Keep alive
        run: |
          Disable-ScheduledTask RunnerMachineProvisioner
          Stop-Process -Name "provisioner" -Force
